# I2C Trackpad
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_I2C_NRFX=y
CONFIG_LOG=y


# A320 Trackpad Mode & Scroll Sensitivity Configuration
CONFIG_A320_START_IN_SCROLL_MODE=y
CONFIG_A320_SCROLL_SCALE_PERCENT=300

# Log via USB or Segger RTT
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=4000
